FROM node:24.11.1-slim

RUN apt-get update && apt-get install -y curl ca-certificates

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
